  stages:
    - build
    - scan
    - push

  variables:
    TWISTLOCK_PASS: cellophane-wrapped-chicken

  docker_build:
    tag: docker-build
    stage: build
    script: docker build -t docker-registry-default.development.preview.stp.hmlr.zone/default/docker-test:1.0 .

  twistlock_scan:
    tag: docker-build
    stage: scan
    script: /usr/local/bin/twistcli images scan --address https://console-twistlock.development.preview.stp.hmlr.zone/ --user peter --password ${TWISTLOCK_PASS} docker-test:1.0

  docker_push:
    tag: docker-build
    stage: push
    script: docker push docker-test:1.0 docker-registry-default.development.preview.stp.hmlr.zone/default/docker-test:1.0
